version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: usof_node
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - usof

  db:
    image: postgres:13
    container_name: usof_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - usof

volumes:
  postgres_data:

networks:
  usof: